# Generated by Django 3.2.6 on 2021-12-04 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20211130_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='following',
            name='subscription',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='subs', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
