# Generated by Django 3.2.6 on 2021-12-21 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_liked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liked',
            old_name='user',
            new_name='username',
        ),
    ]
