# Generated by Django 3.2.6 on 2021-12-22 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_rename_user_liked_username'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='liked',
            unique_together={('username', 'post', 'unliked')},
        ),
    ]
