# Generated by Django 3.2.6 on 2022-01-03 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_alter_liked_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='following',
            name='subscription',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='subs', to=settings.AUTH_USER_MODEL),
        ),
    ]
